### ISSUE TITLE
Uncaught TypeError: i.register is not a function

### ISSUE THREAD

**Issue by jbreitung** [vaadin-component-factory/autocomplete#6]
Hi there,

I added the Maven dependency for the autocomplete component to use it in my Vaadin 14 Flow application. Just after that I was not able to startup my application properly anymore. I am just getting a TypeError in my browsers console:

![image](https://user-images.githubusercontent.com/22149422/104294783-e86ee300-54bf-11eb-9d9f-7284943f31a3.png)

As you can see in the network secion of my browsers debugging tool, all required resources are loaded properly:

![image](https://user-images.githubusercontent.com/22149422/104294956-266c0700-54c0-11eb-91f6-f1a32635e070.png)

It seems that the TypeError is caused by something missing in the Vaadin bundle JS file.

Does anybody know a solution for this? Or may be something broken here? The sample provided by this repo works fine.

Best Regards.

**Comment by jcgueriaud1** [comment]
Closed by https://github.com/vaadin-component-factory/autocomplete/pull/13
