### ISSUE TITLE
License in classes headers should be also changed to apache 2.0

### ISSUE THREAD

**Issue by hfazai** [vaadin-component-factory/autocomplete#7]
As I see that this component is re-released with Apache 2 license. which is really great!

This [commit](https://github.com/vaadin-component-factory/autocomplete/commit/1ae806eb2db1aab0dfbeb874c94723926b72918f) changes the licence of this component but classes headers like [Autocomplete.java](https://github.com/vaadin-component-factory/autocomplete/blob/master/autocomplete/src/main/java/com/vaadin/componentfactory/Autocomplete.java) still with CVALv3. 

Maybe classes headers should be also changed to apache 2.0

**Comment by TatuLund** [comment]
> Maybe classes headers should be also changed to apache 2.0

Yes, they should. Thanks for pointing this out.

**Comment by jcgueriaud1** [comment]
Closed by https://github.com/vaadin-component-factory/autocomplete/pull/13
